### ISSUE TITLE
Correlation Matrix

### ISSUE THREAD

**Issue by yuxue-liu** [a791702141/GATN#1]
Thank you very much for sharing your work. I would like to ask you a question, how is the matrix related to the following figure in the code file generated?
![image](https://github.com/a791702141/GATN/assets/54567030/da9e28a0-7213-4da2-8103-79b7161f28f3)

**Comment by a791702141** [comment]
The coco_adj is a co-occurrence statistics of coco dataset while coco_correlation_adj is cosine similarity based semantic matrix

**Comment by yuxue-liu** [comment]
> The coco_adj is a co-occurrence statistics of coco dataset while coco_correlation_adj is cosine similarity based semantic matrix
I understand. Thanks.
